[workspace]
members = [
    "crates/engine_math",
    "crates/engine_core",
    "crates/engine_render_api",
    "crates/engine_input",
    "crates/engine_render_sw",
    "crates/engine_scene",
    "crates/engine_editor",
]
resolver = "2"

[workspace.package]
license = "MIT"
authors = ["Simple-XX"]
repository = "https://github.com/Simple-XX/SimpleGameEngine"

[profile.dev]
opt-level = 2

[profile.dev.package.image]
opt-level = 3

[profile.dev.package.tobj]
opt-level = 3
